name: Tag, Release and Upload
on:
  push:
    branches:
      - cram2
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.21
        uses: actions/setup-go@v1
        with:
          go-version: 1.21
        id: go
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install cram
        run: |
          python -m pip install --upgrade pip
          pip install cram
      - name: Check out new tag into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.tag_release.outputs.tag }}
      - name: Deps & Build
        shell: bash
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make build-deps
          make build
